# Generated by Django 4.0.2 on 2022-07-01 01:10

import chunked_upload.settings
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to=chunked_upload.settings.default_upload_to),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
